name: LMS v3 Production release

on:
  workflow_dispatch:

jobs:
  release:
    name: Production
    uses: Learning-Lions-2020/lms-v3/.github/workflows/release.yml@main
    with:
      azure-webapp-api-name: wa-lms-v3-production-api
      azure-static-webapp-ui-name: swa-lms-v3-production
      api-url: https://lms-v3-api.citou.se
      version: ${{ github.event.release.tag_name }}
    secrets:
      azure-webapp-api-publish-profile: ${{ secrets.AZURE_WEBAPP_API_PUBLISH_PROFILE_PRODUCTION }}
      azure-static-web-app-ui-deployment-token: ${{ secrets.AZURE_STATIC_WEBAPP_UI_TOKEN_PRODUCTION }}