name: Compago release

env:
  DOTNET_VERSION_GENERAL: '9'
  DOTNET_VERSION_SPECIFIC: '9.0.x'
  API_PROJECT_NAME: Compago.API
  API_NAME: wa-compago-api
  FUNCTION_PROJECT_NAME: Compago.Function
  FUNCTION_NAME: fa-compago

on:
  release:
    types: [published]

jobs:
  build_api:
    name: Compago API Build
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET ${{ env.DOTNET_VERSION_GENERAL }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION_GENERAL }}

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Exclude Compago.Test project
        run: dotnet sln remove Compago.Test/Compago.Test.csproj

      - name: Exclude Compago.Function project
        run: dotnet sln remove Compago.Function/Compago.Function.csproj

      - name: Build ${{env.APP_PROJECT_NAME}}
        run: dotnet build ${{env.API_PROJECT_NAME}} --configuration Release

      - name: Publish with dotnet
        run: dotnet publish --configuration Release --property:PublishDir=${{ env.DOTNET_ROOT }}/${{ env.API_NAME }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.API_NAME }}
          path: ${{ env.DOTNET_ROOT }}/${{ env.API_NAME }}

  deploy_api:
    name: Compago API Deploy
    runs-on: ubuntu-24.04
    needs: build_api

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.API_NAME }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.API_NAME }}
          publish-profile: ${{ secrets.AZURE_COMPAGO_API_PUBLISH_PROFILE }}
          package: .

      - name: Delete build artifact
        if: always()
        uses: geekyeggo/delete-artifact@v5
        with:
            name: ${{ env.API_NAME }}      

  build_deploy_function:
    name: Compago Function Build/Deploy
    runs-on: windows-latest
    needs: [deploy_api]
    
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup .Net ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          pushd './${{ env.FUNCTION_PROJECT_NAME }}'
          dotnet build --configuration Release --output ./output
          popd
      
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: '${{ env.FUNCTION_NAME }}'
          slot-name: 'Production'
          package: '${{ env.FUNCTION_PROJECT_NAME }}/output'
          publish-profile: ${{ secrets.AZURE_COMPAGO_FUNCTION_PUBLISH_PROFILE }}